package main.entities.Plant;

public class GymnospermsPlants extends Plant {
    //Magic number fix
    private static final double HANGING_PROB = 60 / 100.0;
    private static final double OXYGEN_FROM_PLANT = 0.0;

    public GymnospermsPlants(final String name, final double mass) {
        //Superclass's constructor
        super(name, mass);
    }

    /**
     * Calculates the probability that the robot gets stuck in the plants
     * @return hangingProbability
     */
    @Override
    protected double hangingProbability() {
        return HANGING_PROB;
    }

    /**
     * Returns the oxygen level generated by each type of plant
     * @return oxygenFromPlant
     */
    @Override
    protected double oxygenFromPlant() {
        return OXYGEN_FROM_PLANT;
    }

    /**
     * Sum up the oxygen generated by the plant with the oxygen generated
     * depending on the maturity level
     * @return the sum
     */
    @Override
    protected double oxygenLevel() {
        return getMaturityOxygen() + oxygenFromPlant();
    }
}
