package main.entities.Plant;

import main.entities.Air.Air;
import main.entities.Entities;

public abstract class Plant extends Entities {
    //Magic number fix
    private static final double MATURITY_OXYGEN_YOUNG = 0.2;
    private static final double MATURITY_OXYGEN_MATURE = 0.7;
    private static final double MATURITY_OXYGEN_OLD = 0.4;
    private static final double MATURITY_OXYGEN_DEAD = 0.0;
    private static final double NORMALIZING_FACTOR = 100.0;

    private String type; //plant type (Flowering, Gymnosperms, Ferns, Mosses, Algae)
    private String maturityLevel; //plant maturity (Young, Mature, Old, Dead)
    private double maturityOxygen; //oxygen level from plant (depending on the maturity level)
    private double growthLevel; //the level that the plant grows with
    private boolean isScanned; //true if the plant is scanned by the robot
    private boolean isDead; //true if plant died

    public Plant(final String name, final double mass) {
        super(name, mass); //Superclass's constructor
        this.type = null;
        this.maturityLevel = "Young";
        this.maturityOxygen = MATURITY_OXYGEN_YOUNG;
        this.growthLevel = 0.0;
        this.isScanned = false;
        this.isDead = false;
    }

    //Getter and Setter methods for private class fields
    public final String getType() {
        return this.type;
    }
    public final void setType(final String type) {
        this.type = type;
    }
    public final double getMaturityOxygen() {
        return this.maturityOxygen;
    }
    public final boolean getIsDead() {
        return this.isDead;
    }
    public final void setIsDead(final boolean isDead) {
        this.isDead = isDead;
    }
    public final boolean getIsScanned() {
        return this.isScanned;
    }
    public final void setIsScanned(final boolean isScanned) {
        this.isScanned = isScanned;
    }

    /**
     * Calculates the probability that the robot gets stuck in the plants
     * @return hangingProbability
     */
    protected abstract double hangingProbability();

    /**
     * Because hangingProbability is protected, the access to it is made by this method
     * @return hangingProbability
     */
    public double getHangingProbability() {
        return hangingProbability();
    }

    /**
     * Returns the oxygen level generated by each type of plant
     * @return oxygenFromPlant
     */
    protected abstract double oxygenFromPlant();

    /**
     * Sum up the oxygen generated by the plant with the oxygen generated
     * depending on the maturity level
     * @return the sum
     */
    protected abstract double oxygenLevel();

    /**
     * Set the oxygen level generated by the plant at a certain time in life
     */
    protected void setMaturityRate() {
        if (maturityLevel.equals("Young")) {
            maturityOxygen = MATURITY_OXYGEN_YOUNG;
        } else {
            if (maturityLevel.equals("Mature")) {
                maturityOxygen = MATURITY_OXYGEN_MATURE;
            } else {
                if (maturityLevel.equals("Old")) {
                    maturityOxygen = MATURITY_OXYGEN_OLD;
                } else {
                    if (maturityLevel.equals("Dead")) {
                        maturityOxygen = MATURITY_OXYGEN_DEAD;
                    }
                }
            }
        }
    }

    /**
     * Update the maturity level
     */
    protected void growMaturity() {
        if (maturityLevel.equals("Young")) {
            maturityLevel = "Mature";
            setMaturityRate();
        } else {
            if (maturityLevel.equals("Mature")) {
                maturityLevel = "Old";
                setMaturityRate();
            } else {
                if (maturityLevel.equals("Old")) {
                    maturityLevel = "Dead";
                    setIsDead(true);
                    setMaturityRate();
                }
            }
        }
    }

    /**
     * The plant grows with growthLevel
     * @param increaseLevel the level with which the plant grows
     */
    public void grow(final double increaseLevel) {
        if (!isDead) {
            growthLevel += increaseLevel;
            if (growthLevel >= 1.0) {
                growMaturity();
                //resetting the growthLevel after growing the plant
                growthLevel = 0.0;
            }
        }
    }

    /**
     * Interaction Plant - Air (oxygen in the air increases with oxygen produced by the plant)
     * @param air the air with which the plant interacts
     */
    public void interactionAir(final Air air) {
        if (air != null && !getIsDead() && getIsScanned()) {
            double newOxygenLevel = air.getOxygenLevel() + oxygenLevel();
            newOxygenLevel = Math.round(newOxygenLevel * NORMALIZING_FACTOR) / NORMALIZING_FACTOR;
            air.setOxygenLevel(newOxygenLevel);
        }
    }
}
